### ISSUE TITLE
Coursework feedback

### ISSUE THREAD

**Issue by NYBACHOK** [Qewby/constituency_tree_parser#1]
Student: Цигельник Богдан

Для прохідного:
✔️  ! CLI:
✔️ ! Brief Description:
✔️ ! Project Name:
✔️ ! Grammar Rules:
✔️ ! Unit Tests:
✔️ ! Core Files:

Для максимального:
❌  File System:
✔️  Test Coverage:
❌ Error Handling: не роби unwrap у тестах. UPD: це відноситься і до lib.rs також. тільки там ти щей мав використати thiserror
✔️ cargo fmt: 
❌ cargo clippy: після виконання всіх пунктів
✔️ makefile:
❌ Completeness: після виконання всіх пунктів
✔️ Including a diagram or grammar in the Readme.md: 
❌ Documentation:
❌ Publishing: посилання у Readme.md на crates.io

✔️ Курсова може бути зарахована
Бал: 12/25

**Comment by NYBACHOK** [comment]
Оновив

**Comment by NYBACHOK** [comment]
Напиши, якщо погоджуєшся

**Comment by Qewby** [comment]
погоджуюся
